export const ROLES = {
  DIRECCION_GENERAL: 'DIRECCION_GENERAL',
  GERENCIA_HOTEL: 'GERENCIA_HOTEL',
  LIDER_COMERCIAL: 'LIDER_COMERCIAL',
  EJECUTIVO_COMERCIAL: 'EJECUTIVO_COMERCIAL',
  COORDINACION_OPERATIVA: 'COORDINACION_OPERATIVA',
  FINANCIERO: 'FINANCIERO',
  CALIDAD: 'CALIDAD',
  ADMINISTRADOR: 'ADMINISTRADOR',
};

export const ALL_ROLES = Object.values(ROLES);
